### ISSUE TITLE
Adding themes from other mods

### ISSUE THREAD

**Issue by leovoel** [ultraabox/ultrabox_typescript#1]
The ones listed were:

- Modbox
- Sandbox
- Shitbox's 1.0 theme

Are there any others?

**Comment by MainCharacteroftheProblem** [comment]
![image](https://github.com/ultraabox/ultrabox_typescript/assets/121472288/b2707a0a-510a-4757-a645-cbc5b8cd1602)
When added this onto the idea list, I was referring to all of the extra modbox themes, and the older versions of the modbox/sandbox themes (their themes changed over time). 

Looking at it again, the shitbox 1.0 theme is basically identical to the 3.0 theme. I don't think it's necessary.

The worst part about doing this is having to convert the old theme format to the new one, it's really time consuming. I looked through #modded-beepbox some time back and found that someone had made a program/script to automatically convert it, but said person left beepcord, so

That, and the multiple versions of modbox:
https://docs.google.com/presentation/d/10R1VZyhES3W62MxxCaQv9J2Y3zek9qrWAnnCzzLcT54/edit#slide=id.g34e359d4cc_0_79

**Comment by MainCharacteroftheProblem** [comment]
So with the latest update, I've decided to move all of the extra modbox/sandbox themes over to the theme sheet

sooo I'm gonna close this
