### ISSUE TITLE
Add preference that auto-applies every effect?

### ISSUE THREAD

**Issue by MainCharacteroftheProblem** [ultraabox/ultrabox_typescript#125]
As suggested by Green Guy

Needs more thought

**Comment by NelFusion** [comment]
would it make it laggier having all the effects open on every channel?

**Comment by MainCharacteroftheProblem** [comment]
I doubt so. If it does then you'd always be able to turn the preference off

**Comment by MainCharacteroftheProblem** [comment]
or at least not noticeably
