### ISSUE TITLE
Extend chord limit to 12 notes

### ISSUE THREAD

**Issue by bsoap-cat** [ultraabox/ultrabox_typescript#137]

**Comment by bsoap-cat** [comment]
Since you don't feel like doing that at the moment, here's another issue that needs to be addressed:
__Highlighting numbers in tempo causes it to become 0 BPM__
This also turns every measure with at least a note in it to become void of notes.

**Comment by MainCharacteroftheProblem** [comment]
Moving that to #138 and closing this issue
