### ISSUE TITLE
Port AbyssBox's hotdog features.

### ISSUE THREAD

**Issue by choptop84** [ultraabox/ultrabox_typescript#163]
In abyssbox if you click the hotdog a few times the hotdog will randomly explode, turn into a slice of pizza, a donut, or a banana.

**Comment by MainCharacteroftheProblem** [comment]
I don't wanna add any more images that aren't necessary

**Comment by bsoap-cat** [comment]
> In abyssbox if you click the hotdog a few times the hotdog will randomly explode, turn into a slice of pizza, a donut, or a banana.

Is there anyway I can use the Fruitiger Aero theme in Ultrabox?

**Comment by choptop84** [comment]
> > In abyssbox if you click the hotdog a few times the hotdog will randomly explode, turn into a slice of pizza, a donut, or a banana.
> 
> Is there anyway I can use the Fruitiger Aero theme in Ultrabox?

It's possible to copy the code from the abyssbox-source repository and paste it into the custom theme prompt in ultrabox and I believe it'll work fine. Though to save the trouble you could just use abyssbox since it has 99% if not 100% of ultrabox's current features.
