### ISSUE TITLE
There need's to be a updated version of scales

### ISSUE THREAD

**Issue by Nelvinishere** [ultraabox/ultrabox_typescript#166]
customising scales only cannot toggle the actual 1st note (or 0th note) (example C) and instead toggle the rest 2nd (or 1st) note (example C#) -12th note (or 11th) (example B)
Make it much better to use
Goes like this 
t- toggle (empty space)-not toggled
1st Note (main C)-
2nd Note-t
3rd Note-
4th Note-t
5th Note-
6th Note-t
7th Note-
8th Note-t
9th Note-t
10th Note-
11th Note-
12th Note (last B)-t
because of which you can toggle of the C Note so the user have more customised scales.

**Comment by Nelvinishere** [comment]
Writing of which if 12 instead of 11 notes can be toggled, empty would have no notes toggled.

**Comment by Neptendo** [comment]
What do you mean by this? Asking since there's two ways I'm reading this

Do you mean changing the labels from 1st to 11th to something like 2nd to 11th

Or do you mean making it so that the "0th note" can be turned off?

**Comment by Nelvinishere** [comment]
my answer
making it so that the 0th (aka the main key) note can be turned off.

**Comment by Mid-The-Modder** [comment]
I've implemented this myself _however_ I don't think it'll be implemented into UltraBox.
