### ISSUE TITLE
Improve the "auto-detect" import mode

### ISSUE THREAD

**Issue by MainCharacteroftheProblem** [ultraabox/ultrabox_typescript#172]
Despite what the name implies, no logic is done to figure out what format it should be aside from using `jsonFormat`.

**Comment by MainCharacteroftheProblem** [comment]
@Mid-The-Modder also expressed interest in this...?

**Comment by Mid-The-Modder** [comment]
I believed so yeah.
Looks really weird but I was thinking it should be something along the lines of coming up with rulesets to decipher which mod a json comes from and automatically assigning to that mod for auto detect. That would be pretty difficult to brainstorm though and is mostly effective with mods that have their own unique song jsonformats or the json containing something that only exists in one mod.

**Comment by MainCharacteroftheProblem** [comment]
This is a perpetual issue but I'll close it when the first steps are made
