### ISSUE TITLE
Envelopes with a negative integer should be renamed to fractions

### ISSUE THREAD

**Issue by bsoap-cat** [ultraabox/ultrabox_typescript#174]
List of changes:
flare -1 → flare ½
twang -1 → twang ½
swell -1 → swell ½
tremolo 0 → tremolo ½
decay -1 → decay ½
wibble -1 → wibble ½
linear -2 → linear ¼
linear -1 → linear ½
rise -2 → rise ¼
rise -1 → rise ½

**Comment by MainCharacteroftheProblem** [comment]
this change might appeal to @choptop84 or @Mid-The-Modder

**Comment by Mid-The-Modder** [comment]
Eh. Not really. I'd rather work on an envelope system where envelope speed is 'per envelope' so I can get rid of the numbers as a whole, making much more space while giving so much more customizibility.

**Comment by bsoap-cat** [comment]
> Eh. Not really. I'd rather work on an envelope system where envelope speed is 'per envelope' so I can get rid of the numbers as a whole, making much more space while giving so much more customizibility.

sounds like a good idea

**Comment by bsoap-cat** [comment]
> I'd rather work on an envelope system where envelope speed is 'per envelope' so I can get rid of the numbers as a whole, making much more space while giving so much more customizibility.

Adding onto this, perhaps you could add strength and length into this feature. For example, I could change how strong/soft or long/short the punch envelope could be.

**Comment by Mid-The-Modder** [comment]
For Midbox, I am working on an envelope overhaul right now which will have controls for individual envelope speed (duration multiplier), amplitude (strength multiplier), and other special case options for other envelope types. 
![Screenshot 2024-05-19 230403](https://github.com/ultraabox/ultrabox_typescript/assets/141974713/28483238-25e6-4657-a5d2-53db1c7c4695)
Probably will be a while before this is seen in UltraBox as the update isn't even released yet nor has it been tested much and it's all still very unfinished. I find it to be a very good tool though.

**Comment by bsoap-cat** [comment]
> For Midbox, I am working on an envelope overhaul right now which will have controls for individual envelope speed (duration multiplier), amplitude (strength multiplier), and other special case options for other envelope types. ![Screenshot 2024-05-19 230403](https://private-user-images.githubusercontent.com/141974713/332118428-28483238-25e6-4657-a5d2-53db1c7c4695.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzA0NTgsIm5iZiI6MTcxNjQzMDE1OCwicGF0aCI6Ii8xNDE5NzQ3MTMvMzMyMTE4NDI4LTI4NDgzMjM4LTI1ZTYtNDY1Ny1hNWQyLTUzZGIxYzdjNDY5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMjA5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmJjNWE4ZGUxNmRhNjE3NmE2YWRjNmJmZWY1YTVmMDRjNGU5ODVjNzhhZDU2YjZlMDRlMTBhYmM0ZmIzMzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T752zZcoxkjsCxRgZqVm00wSd9lXqVaWjDPT6-AyPVA) Probably will be a while before this is seen in UltraBox as the update isn't even released yet nor has it been tested much and it's all still very unfinished. I find it to be a very good tool though.

Is there a link to this indev phase of midbox?
