### ISSUE TITLE
Port AB's "Frosted Glass" prompt effect

### ISSUE THREAD

**Issue by MainCharacteroftheProblem** [ultraabox/ultrabox_typescript#180]
Either as just theme variables or as a mix of a preference and theme variables

**Comment by choptop84** [comment]
Didn't see this, if you're willing to wait I'd rather get AbyssBox Mobile finished before I do anything else programming wise

**Comment by choptop84** [comment]
https://github.com/ultraabox/ultrabox_typescript/pull/190
