### ISSUE TITLE
Add ramp wave from the FM as an option in the chip preset

### ISSUE THREAD

**Issue by bsoap-cat** [ultraabox/ultrabox_typescript#186]
The ramp wave should be behind or in front of sawtooth instead of after ultrabox overdrive guitar

**Comment by choptop84** [comment]
Adding a new chip type would have to go to the bottom because changing the order of the chip waves causes errors. Otherwise you would have to randomly bump up the song version just because.

**Comment by MainCharacteroftheProblem** [comment]
Likely not going to add this - I'd prefer to focus on #30

**Comment by Mid-The-Modder** [comment]
Isn't the ramp wave just an inverted sawtooth? Not much work to do this honestly, since all you need to do is just invert a sawtooth on the custom chip. The reason it may sound different on FM is because of this inversion.
