### ISSUE TITLE
instrument settings are now scrollable

### ISSUE THREAD

**Issue by bsoap-cat** [ultraabox/ultrabox_typescript#208]
![image](https://github.com/ultraabox/ultrabox_typescript/assets/127647009/e8edc9d4-0a21-4d75-a287-c90174d87604)

**Comment by MainCharacteroftheProblem** [comment]
instrument settings have been scroll-able on certain layouts for a while. in the latest commit I removed scrollbars from the instrument settings so this shouldn't be a problem in the next update
