### ISSUE TITLE
add a way to add sampled with files as in .wav

### ISSUE THREAD

**Issue by ProPlayerEli** [ultraabox/ultrabox_typescript#214]
the best way to add this feature is when you import it it says custom and you cand edit it besides the eq filter the note filter strum type and a few others that don't rely or that aren't specific on the type of editing style as in FM Chip Pluck Strum...

**Comment by MainCharacteroftheProblem** [comment]
Are you talking about being able to drag-and-drop audio files into UB? Unfortunately that won't be possible in the web version due to technical constraints although it will be possible in the offline version (see #99)
