### ISSUE TITLE
Add option to customize rounding in text fields

### ISSUE THREAD

**Issue by bsoap-cat** [ultraabox/ultrabox_typescript#216]
or you could add an option to disable rounding
just an idea

**Comment by MainCharacteroftheProblem** [comment]
You mean like, in the unison text fields? Unfortunately we can't do that without delegating more characters in the song format (which is something I don't want to do...)

**Comment by bsoap-cat** [comment]
> You mean like, in the unison text fields? Unfortunately we can't do that without increasing the number of characters used for the unison storage in the song format (which is something I'd like to avoid...)

The unison text fields and probably every text field that exists

**Comment by MainCharacteroftheProblem** [comment]
This is unlikely to happen, sorry
