### ISSUE TITLE
Keybind to add new Noise channel/Mod Channel

### ISSUE THREAD

**Issue by choptop84** [ultraabox/ultrabox_typescript#234]
I think it's a little inconvenient that you can't just create a new mod channel instantly and instead you have to go through a prompt first to get a mod channel, same thing with noise channels. I believe a new keybind along the lines of Ctrl+Alt+Enter or Shift+Alt+Enter Would suffice.

**Comment by choptop84** [comment]
An alternative would be to have a single mod channel on when a new song is created

**Comment by wdym-lmao** [comment]
shift+alt+enter for noise and ctrl+alt+enter for mods?

**Comment by MainCharacteroftheProblem** [comment]
You can open the Channel Settings prompt by pressing Q?
