### ISSUE TITLE
Add option to change diamond color independently via custom theme

### ISSUE THREAD

**Issue by wdym-lmao** [ultraabox/ultrabox_typescript#236]

**Comment by choptop84** [comment]
add 
```
.loopEditor {
--ui-widget-background: #ffffff;
}```
To your custom theme and you can change the diamond color

**Comment by wdym-lmao** [comment]
> add
> 
> ```
> .loopEditor {
> --ui-widget-background: #ffffff;
> }
> ```
> 
> To your custom theme and you can change the diamond color

![image](https://github.com/user-attachments/assets/59e905cf-d784-4fbd-9769-fd8afc3d1b60)
so do i just paste it where my cursor is or do i have to paste it somewhere else?

**Comment by choptop84** [comment]
I do not see a cursor in this image, but you want to place this after the `:root {}` that contains all of the colors.

**Comment by wdym-lmao** [comment]
so it should look like this?
![image](https://github.com/user-attachments/assets/421c6fae-d75f-43a0-a469-50e74512fcd8)

**Comment by choptop84** [comment]
No I said after the root not inside of it...

**Comment by choptop84** [comment]
Do you see the end of the entire bit of text and how it ends with `}`? Place it after that

**Comment by wdym-lmao** [comment]
> Do you see the end of the entire bit of text and how it ends with `}`? Place it after that

gotcha
