### ISSUE TITLE
New layout similar to long

### ISSUE THREAD

**Issue by leovoel** [ultraabox/ultrabox_typescript#33]
...but with a larger area combining the song settings and the instrument settings. The mockup shared on the BeepBox Discord was this:

![Layout mockup](https://cdn.discordapp.com/attachments/317504809433300992/1128781860076531833/image.png)

What should it be called?

**Comment by choptop84** [comment]
This is in AbyssBox now, which'll eventually cause it to get ported to UltraBox, this can be resolved now.
