### ISSUE TITLE
Pull the latest BeepBox changes

### ISSUE THREAD

**Issue by MainCharacteroftheProblem** [ultraabox/ultrabox_typescript#83]
We were planning to just leave this to Jummbus, but it's been nearly two months since the release of 4.2, and no Jummbox updates have come out recently, so I guess the responsibility lies on us. Other then just merging the changes and fixing any conflicts, we'll have to add modulator support for supersaws.

It would probably be worth contacting Jummbus about this beforehand.

**Comment by MainCharacteroftheProblem** [comment]
Not sure if I should pin this issue or set it as a milestone for the next version

**Comment by Neptendo** [comment]
i am super late but

Question, if we end up doing it first would that actually like allow Jummbus to just copy over the code from us into Jummbox?

I mean it wouldn't be the first time Jummbus added something to Jummbox from a Jummbox Mod (See: Goldbox FM waves)
